/**
 * Project seed rows (Round 4 content). Text is applied verbatim from the
 * operator's brief. cover_url and gallery_urls are deliberately absent: the
 * seed never touches images, which the operator manages through /admin.
 */
export interface ProjectSeed {
  slug: string;
  title: string;
  subtitle: string;
  client_name: string | null;
  client_public: boolean;
  category: "Voice agents" | "Lead generation" | "Chatbots" | "Workflows" | "Web apps";
  summary: string;
  body: string;
  features: string[];
  results: string[];
  stack: string[];
  use_case: string;
  featured: boolean;
  published: boolean;
  sort_order: number;
}

export const projectSeeds: ProjectSeed[] = [
  {
    slug: "ai-inbound-calling",
    title: "Inbound calling agent for a medical practice",
    subtitle: "Elite VCM",
    category: "Voice agents",
    client_name: "Elite VCM",
    client_public: true,
    use_case: "Clinics, telehealth providers, wellness centres",
    summary: "A voice agent that answers every inbound call for a medical practice, handles patient questions, books appointments and updates the CRM while the caller is still on the line.",
    body: "Elite VCM was missing patient calls outside office hours and losing bookings to voicemail. We built a voice agent that picks up every inbound call, answers the common questions about services, hours and locations, and books or reschedules appointments directly.\n\nEach call is logged and the patient record is updated in the CRM as the conversation happens. When a caller needs a person, the agent takes a message or transfers the call.",
    features: ["Answers inbound calls 24 hours a day", "Books and reschedules appointments", "Answers questions about services, hours and locations", "Updates the CRM during the call", "Takes a message or transfers when a person is needed", "Call log and summary for every conversation"],
    results: ["No missed calls outside office hours", "Bookings taken without staff on the line", "Every call logged and summarised"],
    stack: ["Vapi", "n8n", "Airtable", "HubSpot"],
    featured: true,
    published: true,
    sort_order: 1,
  },
  {
    slug: "outbound-calling-agent",
    title: "Outbound follow-up calls for patient outreach",
    subtitle: "Elite VCM",
    category: "Voice agents",
    client_name: "Elite VCM",
    client_public: true,
    use_case: "Clinics, insurance follow-ups, wellness check-ins",
    summary: "An outbound agent that calls patients from a list for reminders, care follow-ups and health updates, then sends a follow-up email and logs the outcome.",
    body: "Follow-up calls were a manual job that never got fully done. We built an outbound agent that works from the practice's patient list, calls each person with the right context, and handles appointment reminders, care-plan follow-ups and health updates.\n\nAfter each call it sends a personalised follow-up email and writes the result back to the sheet, so the team can see who was reached, who needs a callback and who confirmed.",
    features: ["Calls patients from a Google Sheet list", "Context-aware scripts per patient", "Appointment reminders and care follow-ups", "Follow-up email after every call", "Outcome written back to the list", "Runs on a schedule without staff involvement"],
    results: ["Follow-ups completed on schedule instead of when staff had time", "Fewer no-shows through automated reminders", "Full record of every attempt and outcome"],
    stack: ["Vapi", "n8n", "Gemini", "Google Sheets", "Gmail"],
    featured: true,
    published: true,
    sort_order: 2,
  },
  {
    slug: "real-estate-calling-agent",
    title: "Calling agent for a US real estate company",
    subtitle: "USA BUYS LAND",
    category: "Voice agents",
    client_name: "USA BUYS LAND",
    client_public: true,
    use_case: "Real estate agencies, land buyers, property managers",
    summary: "A calling agent that phones website visitors within moments of their enquiry, answers property questions, qualifies the lead and passes serious buyers to the team.",
    body: "USA BUYS LAND gets enquiries through its website at all hours, and speed matters: a lead called back an hour later is often gone. We built an agent that calls each new enquiry straight away, answers questions about the property and the process, and asks the qualifying questions the team would ask.\n\nQualified leads are handed to the sales team with notes; the rest are followed up automatically. Every conversation is logged against the lead.",
    features: ["Calls new website enquiries immediately", "Answers property and process questions", "Qualifies the lead with the team's own questions", "Hands qualified buyers to sales with notes", "Logs every call against the lead"],
    results: ["Enquiries answered in minutes, around the clock", "Sales team spends its time on qualified buyers only"],
    stack: ["Vapi", "n8n", "CRM integration"],
    featured: true,
    published: true,
    sort_order: 3,
  },
  {
    slug: "linkedin-lead-generation",
    title: "LinkedIn lead research and personalised outreach",
    subtitle: "From a profile link to a sent email",
    category: "Lead generation",
    client_name: null,
    client_public: false,
    use_case: "B2B sales teams, agencies, consultants",
    summary: "Paste a LinkedIn profile link into a form and the system researches the person, finds and verifies their email, writes a personalised message and sends it.",
    body: "Prospecting by hand means reading a profile, hunting for an email, writing a message and sending it, one person at a time. This workflow does all of it from a single input: the LinkedIn profile URL.\n\nIt pulls the name, role and company, discovers and validates a professional email address, writes an outreach email tailored to that person's background, and sends it through the client's Gmail. Each lead and the message sent are recorded for follow-up.",
    features: ["Profile parsing from a LinkedIn URL", "Email discovery and validation", "Personalised outreach written per lead", "Sent from the client's own Gmail", "Every lead and message logged"],
    results: ["Prospecting reduced to pasting a link", "Consistent, personalised first messages at any volume"],
    stack: ["n8n", "OpenAI", "Gmail", "Google Sheets"],
    featured: true,
    published: true,
    sort_order: 4,
  },
  {
    slug: "lead-scraper-automation",
    title: "Lead scraper that fills a spreadsheet from a form",
    subtitle: "Target audience in, ready-to-use leads out",
    category: "Lead generation",
    client_name: null,
    client_public: false,
    use_case: "Sales and marketing teams, agencies, startups",
    summary: "Submit a form with the audience, industry and region you want, and the system scrapes matching leads and writes a clean, organised list into Google Sheets.",
    body: "Building prospect lists by hand is slow and inconsistent. This workflow takes a short form (who you want to reach, where, in which industry), turns it into search queries, scrapes matching businesses and contacts through Apify, and writes the results into a Google Sheet ready for outreach.\n\nRuns are repeatable, so a team can request a fresh list whenever it needs one.",
    features: ["Form-based targeting: audience, industry, region", "Search queries generated from the request", "Scraping through Apify", "Clean rows written to Google Sheets", "Repeatable runs"],
    results: ["Prospect lists on demand instead of days of manual research", "Data arrives structured and ready to use"],
    stack: ["n8n", "Apify", "Google Sheets", "OpenAI"],
    featured: true,
    published: true,
    sort_order: 5,
  },
  {
    slug: "slack-chatbot",
    title: "Slack assistant that answers team questions",
    subtitle: "Context-aware replies inside the channels you already use",
    category: "Chatbots",
    client_name: null,
    client_public: false,
    use_case: "Teams and companies running on Slack",
    summary: "A Slack bot that watches chosen channels, filters for real questions and answers them in the thread, with memory of the conversation so follow-ups make sense.",
    body: "Teams lose time answering the same questions in Slack. This bot listens in selected channels, screens messages so only real questions are handled, and replies in the same thread with an answer grounded in the conversation so far.\n\nFilters control what it responds to, and it can be pointed at internal documentation so answers reflect how the company actually works.",
    features: ["Slack trigger on selected channels", "Filters so only relevant messages are answered", "Conversation memory for follow-up questions", "Replies in the same thread", "Configurable scope and tone"],
    results: ["Common questions answered without interrupting a colleague", "Consistent answers across the team"],
    stack: ["n8n", "Slack API", "Gemini"],
    featured: true,
    published: true,
    sort_order: 6,
  },
  {
    slug: "email-responder",
    title: "Email responder and attachment summariser",
    subtitle: "Reads the attachment, drafts the reply, logs it",
    category: "Workflows",
    client_name: null,
    client_public: false,
    use_case: "Professionals and teams handling heavy inbound email",
    summary: "Watches an inbox, reads PDF and Word attachments, writes a short summary and a draft reply, and logs every email in a sheet.",
    body: "Inboxes with attachments eat time: open the file, read it, reply, file it. This workflow captures each incoming email, extracts the key points from any PDF or Word attachment, writes a concise summary and a suggested reply, and records everything in Google Sheets.\n\nReplies can be sent automatically for routine cases or held for a person to approve.",
    features: ["Inbox monitoring", "Attachment reading for PDF and Word", "Summary and draft reply per email", "Send automatically or hold for approval", "Log of every email in Google Sheets"],
    results: ["Attachments never go unread", "Faster replies with less time in the inbox"],
    stack: ["n8n", "Gmail", "OpenAI", "Google Sheets"],
    featured: false,
    published: true,
    sort_order: 7,
  },
  {
    slug: "reddit-lead-extractor",
    title: "Reddit lead finder for freelance and hiring posts",
    subtitle: "Weekly scan of r/forhire and r/hiring",
    category: "Lead generation",
    client_name: null,
    client_public: false,
    use_case: "Freelancers, agencies, recruiters",
    summary: "Scans hiring subreddits every week, picks out posts that match your skills, and writes the title, budget and contact details into a Google Sheet.",
    body: "Good gigs get posted on Reddit and disappear under new posts within a day. This agent checks r/forhire and r/hiring on a schedule, matches posts against a skills list, and extracts the essentials: title, budget, contact, link.\n\nMatches land in a Google Sheet, so outreach can start the same day.",
    features: ["Scheduled weekly scan", "Skill-based matching", "Title, budget and contact extracted", "Results in Google Sheets"],
    results: ["Relevant posts found without checking Reddit by hand"],
    stack: ["n8n", "Reddit", "OpenAI", "Google Sheets"],
    featured: false,
    published: true,
    sort_order: 8,
  },
  {
    slug: "ai-mock-sales-training",
    title: "Sales training app with AI roleplay",
    subtitle: "Elite VCM",
    category: "Web apps",
    client_name: "Elite VCM",
    client_public: true,
    use_case: "Sales teams and training departments",
    summary: "A web app where sales reps practise calls against an AI customer, get scored on each conversation, and managers see who is ready for real leads.",
    body: "New reps were learning on live leads. We built a training app where they practise instead: an AI customer plays out realistic calls, raises objections and reacts to how the rep handles them.\n\nEach session is scored and broken down so the rep sees what to improve. A readiness score tells managers when someone is ready for real calls, and a dashboard tracks the whole team.",
    features: ["Live AI roleplay calls", "Objection handling practice", "Scored breakdown after each session", "Readiness score per rep", "Manager dashboard"],
    results: ["Reps practise before they touch a real lead", "Managers decide readiness from data rather than gut feel"],
    stack: ["React", "Node.js", "OpenAI"],
    featured: false,
    published: true,
    sort_order: 9,
  },
  {
    slug: "linkedin-post-generator",
    title: "LinkedIn post and image generator",
    subtitle: "From a one-line idea to a ready post",
    category: "Workflows",
    client_name: null,
    client_public: false,
    use_case: "Founders, marketers, consultants",
    summary: "Type a short idea and an image prompt; the workflow writes a LinkedIn post in your tone, generates a matching image and adds hashtags, ready to publish.",
    body: "Staying consistent on LinkedIn fails when every post starts from a blank page. This workflow turns a one-line idea into a finished post: written for a professional audience in the user's own tone, paired with a generated image, and finished with relevant hashtags.",
    features: ["Post written from a one-line idea", "Tone set per user", "Matching image generated", "Hashtags added", "Output ready to paste or schedule"],
    results: ["Posting stays consistent without hours of writing"],
    stack: ["n8n", "OpenAI", "Image generation"],
    featured: false,
    published: true,
    sort_order: 10,
  },
  {
    slug: "social-media-automation",
    title: "Instagram and YouTube posting pipeline",
    subtitle: "From a spreadsheet row to a published reel",
    category: "Workflows",
    client_name: null,
    client_public: false,
    use_case: "Coaches, educators, brand pages",
    summary: "Reads content from a Google Sheet, generates a reel in Canva, and publishes it to Instagram and YouTube on a schedule.",
    body: "Daily posting by hand does not survive a busy week. This pipeline pulls the next item from a Google Sheet, builds a reel with Canva, and uploads it to Instagram and YouTube at the scheduled time, then marks the row as posted.",
    features: ["Content queue in Google Sheets", "Reel generated in Canva", "Posted to Instagram and YouTube", "Scheduled and hands-free", "Row marked as published"],
    results: ["A full week of posts from one sitting"],
    stack: ["n8n", "Canva", "Instagram API", "YouTube API", "Google Sheets"],
    featured: false,
    published: true,
    sort_order: 11,
  },
  {
    slug: "youtube-scraper",
    title: "YouTube channel and video research",
    subtitle: "Channel stats, video metrics and transcripts in a sheet",
    category: "Workflows",
    client_name: null,
    client_public: false,
    use_case: "Creators, marketers, researchers",
    summary: "Give it a channel and it pulls subscriber and view counts, per-video metrics and full transcripts into Google Sheets for research and repurposing.",
    body: "Competitor research on YouTube means clicking through dozens of videos. This workflow takes a channel, collects its overall numbers and each video's views, likes, comments and publish date, and pulls the transcripts so the content itself can be analysed or repurposed.",
    features: ["Channel-level metrics", "Per-video metrics", "Transcript extraction", "Output to Google Sheets"],
    results: ["A channel's full picture in one sheet instead of a day of clicking"],
    stack: ["n8n", "YouTube API", "Google Sheets"],
    featured: false,
    published: true,
    sort_order: 12,
  },
  {
    slug: "news-scraper",
    title: "News monitor with sentiment alerts",
    subtitle: "Filtered headlines to WhatsApp, Telegram or email",
    category: "Workflows",
    client_name: null,
    client_public: false,
    use_case: "Founders, analysts, communications teams",
    summary: "Scrapes the latest news on chosen topics, tags each story as positive, negative or neutral, and sends the headlines that matter to WhatsApp, Telegram or email.",
    body: "Following news on a topic means either constant checking or missing things. This agent collects new articles on chosen keywords, scores their sentiment, and delivers a short filtered digest to the channel the client prefers.",
    features: ["Keyword-based collection", "Sentiment scoring", "Digest to WhatsApp, Telegram or email", "Runs on a schedule"],
    results: ["The important stories arrive; the noise does not"],
    stack: ["n8n", "OpenAI", "WhatsApp", "Telegram"],
    featured: false,
    published: true,
    sort_order: 13,
  },
  {
    slug: "invoice-generator",
    title: "Invoice data extraction into Google Sheets",
    subtitle: "Upload a file, get structured rows",
    category: "Workflows",
    client_name: null,
    client_public: false,
    use_case: "Finance teams, bookkeepers, agencies",
    summary: "Drop an invoice into a Google Drive folder and the workflow extracts the supplier, dates, totals and line items into a structured sheet.",
    body: "Typing invoice details into a spreadsheet is slow and error-prone. This workflow watches a Drive folder, reads each new invoice, extracts the header fields and every line item, and appends them as clean rows in Google Sheets.",
    features: ["Drive folder trigger", "Header fields and line items extracted", "Structured rows in Google Sheets", "Handles PDF and image invoices"],
    results: ["Invoice data captured without retyping"],
    stack: ["n8n", "Google Drive", "OpenAI", "Google Sheets"],
    featured: false,
    published: true,
    sort_order: 14,
  },
  {
    slug: "json-prompts-generator",
    title: "Plain-text to structured JSON prompt builder",
    subtitle: "For teams building their own AI workflows",
    category: "Workflows",
    client_name: null,
    client_public: false,
    use_case: "Developers, workflow builders, data teams",
    summary: "Describe what you want in plain language and the workflow returns a validated JSON prompt, stored in a sheet for reuse.",
    body: "Writing structured prompts by hand is fiddly. This workflow takes a plain-text description from a form, builds a complete JSON prompt to a set schema, checks it, and saves it to Google Sheets so it can be reused across projects.",
    features: ["Form input in plain language", "Schema-based JSON output", "Validation before saving", "Stored in Google Sheets"],
    results: ["Reusable prompts without hand-editing JSON"],
    stack: ["n8n", "OpenAI", "Google Sheets"],
    featured: false,
    published: true,
    sort_order: 15,
  },
  {
    slug: "mia-ai-assistant",
    title: "Voice-driven personal assistant on Telegram",
    subtitle: "Email, calendar, contacts and records from one voice note",
    category: "Chatbots",
    client_name: null,
    client_public: false,
    use_case: "Founders and busy professionals",
    summary: "Send a voice note on Telegram and the assistant reads or sends email, manages calendar events, searches the web and updates Airtable, with memory across the conversation.",
    body: "This assistant takes a voice message on Telegram, transcribes it, works out what is being asked and does it across the user's tools: Gmail, Google Calendar, Contacts, Tasks and Airtable. It remembers context, so a follow-up like \"move that to Friday\" works.\n\nBuilt with n8n as a showcase of what a single agent can run across many apps.",
    features: ["Voice input via Telegram", "Reads, drafts and sends email", "Creates and updates calendar events", "Searches live information", "Airtable, Contacts and Tasks integration", "Conversation memory"],
    results: ["Everyday admin handled from one voice message"],
    stack: ["n8n", "OpenAI", "Whisper", "Telegram", "Google Workspace", "Airtable"],
    featured: false,
    published: true,
    sort_order: 16,
  },
];

export const settingSeeds: { key: string; value: Record<string, unknown> }[] = [
  {
    key: "contact",
    value: {
      email: "samiautomates@gmail.com",
      whatsapp: "https://wa.me/923103011955",
      linkedin: "https://www.linkedin.com/in/samiullahmemon-956393209",
      x: "https://x.com/MemonSamiullah4",
    },
  },
  {
    key: "fiverr",
    value: {
      profile_url: "https://www.fiverr.com/ismailmemon1",
      rating: 4.9,
      reviews: 61,
      level: "Level 2",
    },
  },
];
