/**
 * Seed rows converted from the former src/lib/portfolio-data.ts (Round 1 state).
 * Text is copied verbatim except the invoice project title (it extracts invoice
 * data, it does not generate invoices). Placeholder client names were dropped:
 * client_name is null and client_public false unless the client is real.
 */
export interface ProjectSeed {
  slug: string;
  title: string;
  subtitle: string;
  client_name: string | null;
  client_public: boolean;
  category: string;
  summary: string;
  body: string;
  features: string[];
  results: string[];
  stack: string[];
  use_case: string;
  cover_url: string;
  featured: boolean;
  published: boolean;
  sort_order: number;
}

export const projectSeeds: ProjectSeed[] = [
  {
    slug: "ai-inbound-calling",
    title: "AI Inbound Calling System",
    subtitle: "Elite VCM",
    client_name: "Elite VCM",
    client_public: true,
    category: "Voice AI",
    summary: "Autonomous AI calling system for medical practices that answers patient inquiries, schedules appointments, and provides 24/7 support.",
    body: "I developed a smart, fully autonomous AI Inbound Calling Agent for Elite VCM, designed to instantly respond to patient inquiries and assist website visitors with medical support, appointment scheduling, and FAQs. This system answers inbound calls automatically, offers intelligent voice assistance, and connects with CRM to update patient interactions in real-time.",
    features: ["Answers inbound calls automatically", "Intelligent voice assistance", "Appointment booking & scheduling", "Real-time CRM integration", "24/7 availability", "Context-aware responses"],
    results: ["10x more conversions", "24/7 medical support", "Zero missed leads"],
    stack: ["Voice AI", "NLP", "CRM Integration", "Airtable/HubSpot"],
    use_case: "Medical practices, clinics, telehealth providers",
    cover_url: "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&q=80&w=800&h=600",
    featured: true,
    published: true,
    sort_order: 1,
  },
  {
    slug: "outbound-calling-agent",
    title: "Outbound Calling Agent",
    subtitle: "Medical Outreach Automation",
    client_name: "Elite VCM",
    client_public: true,
    category: "Voice AI",
    summary: "Automated outbound calling system for medical follow-ups and patient engagement campaigns with intelligent voice handling.",
    body: "For Elite VCM, I developed a powerful AI Outbound Calling Agent that automates patient follow-ups and medical outreach campaigns. This system handles automated outbound calling to patient lists, provides intelligent voice responses, logs calls in real-time, and ensures compliance with healthcare communication regulations.",
    features: ["Automated outbound calling", "Intelligent voice responses", "Patient database integration", "Real-time call logging", "Healthcare compliance", "Customizable call scripts"],
    results: ["Automated workflows", "Reduced manual workload", "Improved engagement"],
    stack: ["Voice AI", "Patient Database", "CRM Systems"],
    use_case: "Healthcare providers, medical outreach teams",
    cover_url: "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&q=80&w=800&h=600",
    featured: true,
    published: true,
    sort_order: 2,
  },
  {
    slug: "ai-mock-sales-training",
    title: "AI-Powered Sales Training",
    subtitle: "EliteVCM Training Platform",
    client_name: "EliteVCM",
    client_public: true,
    category: "Enterprise AI",
    summary: "Interactive AI-powered sales training platform with realistic scenarios, real-time feedback, and performance analytics.",
    body: "I built an AI-powered mock sales training web application for EliteVCM that helps sales teams practice and improve their skills through realistic AI-driven scenarios. The application features interactive sales scenarios, provides real-time feedback, tracks performance analytics, and allows customizable training modules.",
    features: ["Interactive AI scenarios", "Real-time feedback", "Performance analytics", "Customizable modules", "Team integration", "Leaderboards"],
    results: ["Accelerated training", "Consistent skill development", "Measurable improvements"],
    stack: ["AI/ML", "React", "Web Framework"],
    use_case: "Sales teams, training departments",
    cover_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=800&h=600",
    featured: true,
    published: true,
    sort_order: 3,
  },
  {
    slug: "real-estate-calling-agent",
    title: "Real Estate AI Calling Agent",
    subtitle: "USA BUYS LAND",
    client_name: "USA BUYS LAND",
    client_public: true,
    category: "Voice AI",
    summary: "Intelligent real estate calling system that qualifies leads, schedules property viewings, and manages inquiries automatically.",
    body: "Developed a smart calling system for USA BUYS LAND, a U.S.-based real estate agency, automating lead qualification and property inquiries. The system handles automated inbound call handling, performs lead qualification through conversational AI, and synchronizes with CRM for lead tracking.",
    features: ["Automated call handling", "Lead qualification", "Property information delivery", "Appointment scheduling", "CRM synchronization", "Multi-property support"],
    results: ["Increased lead capture", "24/7 availability", "Improved satisfaction"],
    stack: ["Voice AI", "CRM Integration", "Real Estate DB"],
    use_case: "Real estate agencies, property management",
    cover_url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=800&h=600",
    featured: true,
    published: true,
    sort_order: 4,
  },
  {
    slug: "linkedin-post-generator",
    title: "LinkedIn Post & Image Generator",
    subtitle: "AI Content Automation",
    client_name: null,
    client_public: false,
    category: "Content AI",
    summary: "AI agent that generates professional LinkedIn posts and images from simple text ideas, optimizing for engagement.",
    body: "This AI agent streamlines LinkedIn content creation by turning simple ideas into professional posts and images ready to publish. The system generates text-to-post content, automatically creates images, optimizes hashtags, and allows tone and style customization.",
    features: ["Text-to-post generation", "Image creation", "Hashtag optimization", "Tone customization", "Batch scheduling", "Analytics integration"],
    results: ["80% time savings", "Consistent posting", "Improved engagement"],
    stack: ["AI/ML", "Image Generation", "LinkedIn API"],
    use_case: "Content creators, B2B marketers, thought leaders",
    cover_url: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&q=80&w=800&h=600",
    featured: true,
    published: true,
    sort_order: 5,
  },
  {
    slug: "linkedin-lead-generation",
    title: "LinkedIn Lead Generation",
    subtitle: "AI-Powered Outreach",
    client_name: null,
    client_public: false,
    category: "Automation",
    summary: "Automated LinkedIn lead generation and cold outreach system with AI-personalized messaging and campaign tracking.",
    body: "This project demonstrates how AI can revolutionize lead generation and cold outreach on LinkedIn, automating prospect research and personalized messaging. The system performs AI-powered prospect research, automates connection requests, and generates AI-created cold outreach messages.",
    features: ["Prospect research", "Automated connections", "AI-generated messages", "Lead scoring", "Campaign tracking", "Response optimization"],
    results: ["Automated workflows", "Personalized at scale", "Higher response rates"],
    stack: ["AI/ML", "LinkedIn API", "Automation"],
    use_case: "Sales teams, B2B companies, agencies",
    cover_url: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&q=80&w=800&h=600",
    featured: true,
    published: true,
    sort_order: 6,
  },
  {
    slug: "lead-scraper-automation",
    title: "Lead Scraper Automation",
    subtitle: "AI Web Scraping & Data Collection",
    client_name: null,
    client_public: false,
    category: "Automation",
    summary: "Automated lead scraping system that turns form submissions into organized prospect lists in Google Sheets.",
    body: "This project automates the entire lead generation process with AI and web scraping. When a user submits a form, the AI agent takes over, queries sources via Apify API, scrapes high-quality leads, and automatically logs them into Google Sheets.",
    features: ["Form-based targeting", "AI processing", "Real-time scraping", "Google Sheets integration", "Data validation", "Scalable workflow"],
    results: ["Instant lead discovery", "Ready-to-use data", "Eliminated manual work"],
    stack: ["Apify API", "Google Sheets", "AI/ML", "Web Scraping"],
    use_case: "Sales teams, startups, agencies",
    cover_url: "https://images.unsplash.com/photo-1551288049-bbda4833effb?auto=format&fit=crop&q=80&w=800&h=600",
    featured: false,
    published: true,
    sort_order: 7,
  },
  {
    slug: "youtube-scraper",
    title: "YouTube Analytics & Scraper",
    subtitle: "AI Data Extraction & Analysis",
    client_name: null,
    client_public: false,
    category: "Automation",
    summary: "Automated YouTube analytics and transcript extraction system that provides competitor analysis and content insights.",
    body: "This advanced AI agent, built in n8n, automates YouTube data extraction and analysis. It scrapes complete channel insights, individual video details, and extracts video transcripts for deeper content analysis.",
    features: ["Channel metrics extraction", "Video analytics", "Transcript extraction", "Sentiment analysis", "Data organization", "Competitor analysis"],
    results: ["Automated analysis", "Actionable insights", "Time-saving"],
    stack: ["n8n", "YouTube API", "Data Analysis", "Google Sheets"],
    use_case: "Content creators, marketers, researchers",
    cover_url: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?auto=format&fit=crop&q=80&w=800&h=600",
    featured: false,
    published: true,
    sort_order: 8,
  },
  {
    slug: "slack-chatbot",
    title: "Slack AI Chatbot",
    subtitle: "Team Communication Automation",
    client_name: null,
    client_public: false,
    category: "Enterprise AI",
    summary: "Intelligent Slack chatbot that automates team communications and streamlines workflow integration.",
    body: "This project showcases an AI-powered Slack chatbot built to automate responses and streamline team communications. The chatbot features intelligent message understanding, automated response generation, and integration with team workflows.",
    features: ["Message understanding", "Automated responses", "Workflow integration", "Context-aware replies", "Learning capability", "Custom commands"],
    results: ["Reduced response time", "Consistent communication", "Improved efficiency"],
    stack: ["Slack API", "AI/ML", "NLP"],
    use_case: "Teams, organizations, companies",
    cover_url: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=800&h=600",
    featured: false,
    published: true,
    sort_order: 9,
  },
  {
    slug: "social-media-automation",
    title: "Social Media Automation",
    subtitle: "Instagram & YouTube Posting",
    client_name: null,
    client_public: false,
    category: "Content AI",
    summary: "Powerful AI agent that automates Instagram and YouTube posting, scheduling, and engagement tracking.",
    body: "I create powerful AI agents that automate Instagram and YouTube posting, scheduling, and engagement. The system handles automated content scheduling, cross-platform posting, and AI-generated captions.",
    features: ["Automated scheduling", "Cross-platform posting", "AI captions", "Hashtag optimization", "Engagement tracking", "Content calendar"],
    results: ["Consistent posting", "Increased reach", "Time savings"],
    stack: ["Instagram API", "YouTube API", "Automation"],
    use_case: "Content creators, influencers, brands",
    cover_url: "https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?auto=format&fit=crop&q=80&w=800&h=600",
    featured: false,
    published: true,
    sort_order: 10,
  },
  {
    slug: "news-scraper",
    title: "AI News Scraper",
    subtitle: "Sentiment Analysis & Monitoring",
    client_name: null,
    client_public: false,
    category: "Automation",
    summary: "Automated news monitoring system with AI sentiment analysis providing real-time market insights.",
    body: "This AI agent continuously scrapes the latest global news, analyzes sentiment, and delivers actionable insights for market research, competitive intelligence, and trend tracking.",
    features: ["Real-time scraping", "Sentiment analysis", "Trend identification", "Auto alerts", "Data visualization", "Keyword monitoring"],
    results: ["Automated monitoring", "Real-time insights", "Data-driven decisions"],
    stack: ["Web Scraping", "Sentiment Analysis", "AI/ML", "Data Viz"],
    use_case: "Researchers, analysts, media professionals",
    cover_url: "https://images.unsplash.com/photo-1504711432819-08479a55c0a7?auto=format&fit=crop&q=80&w=800&h=600",
    featured: false,
    published: true,
    sort_order: 11,
  },
  {
    slug: "invoice-generator",
    title: "Invoice Data Extraction",
    subtitle: "Business Process Automation",
    client_name: null,
    client_public: false,
    category: "Automation",
    summary: "Automated invoice generation and management system that streamlines billing and payment tracking.",
    body: "This automation simplifies invoice processing for businesses by automatically generating, organizing, and managing invoices through AI, reducing manual errors and speeding up the billing cycle.",
    features: ["Auto generation", "Template customization", "Payment tracking", "Multi-currency", "Auto archiving", "Invoice numbering"],
    results: ["Reduced errors", "Faster processing", "Better cash flow"],
    stack: ["Automation", "Invoice Processing", "Database"],
    use_case: "Freelancers, agencies, businesses",
    cover_url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=800&h=600",
    featured: false,
    published: true,
    sort_order: 12,
  },
  {
    slug: "json-prompts-generator",
    title: "JSON Prompts Generator",
    subtitle: "AI Workflow Automation",
    client_name: null,
    client_public: false,
    category: "Automation",
    summary: "Converts natural language commands into structured JSON prompts ready for API integration.",
    body: "This workflow turns plain text commands into structured JSON prompts ready for API integration and automation workflows, streamlining the bridge between human language and technical schemas.",
    features: ["NL to JSON conversion", "Template generation", "Validation", "API integration", "Batch processing", "Schema customization"],
    results: ["Streamlined integration", "Reduced formatting", "Faster development"],
    stack: ["AI/ML", "JSON Processing", "Automation"],
    use_case: "Developers, workflow builders, data teams",
    cover_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800&h=600",
    featured: false,
    published: true,
    sort_order: 13,
  },
  {
    slug: "email-responder",
    title: "Email Responder & Summarizer",
    subtitle: "Email Automation",
    client_name: null,
    client_public: false,
    category: "Enterprise AI",
    summary: "Automated email management system that reads, summarizes attachments, and generates responses.",
    body: "This AI agent automates the entire email workflow by monitoring inboxes, summarizing attachments, and generating intelligent draft responses, significantly reducing time spent on administrative tasks.",
    features: ["Email monitoring", "Attachment summarization", "AI replies", "Priority sorting", "Email integration", "Smart organization"],
    results: ["Reduced email time", "Never miss attachments", "Faster responses"],
    stack: ["Email API", "AI/ML", "Attachment Processing"],
    use_case: "Professionals, customer service, teams",
    cover_url: "https://images.unsplash.com/photo-1557200134-90327ee9fafa?auto=format&fit=crop&q=80&w=800&h=600",
    featured: false,
    published: true,
    sort_order: 14,
  },
  {
    slug: "mia-ai-assistant",
    title: "Mia - AI Personal Assistant",
    subtitle: "Comprehensive Automation",
    client_name: null,
    client_public: false,
    category: "Enterprise AI",
    summary: "Comprehensive AI personal assistant that manages emails, calendar, tasks, and integrations via voice commands.",
    body: "Imagine an assistant that doesn't just reply to queries, but actually runs your digital life end-to-end. Mia is a true command center for everything from emails to CRM updates.",
    features: ["Email management", "Calendar events", "Real-time search", "Airtable integration", "Google integration", "Voice commands"],
    results: ["End-to-end automation", "Intelligent behavior", "Multi-app integration"],
    stack: ["OpenAI", "Whisper", "Telegram", "Google", "Airtable"],
    use_case: "Professionals, entrepreneurs",
    cover_url: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&q=80&w=800&h=600",
    featured: false,
    published: true,
    sort_order: 15,
  },
];

export const settingSeeds: { key: string; value: Record<string, unknown> }[] = [
  {
    key: "contact",
    value: {
      email: "samiautomates@gmail.com",
      whatsapp: "https://wa.me/923103011955",
      linkedin: "https://www.linkedin.com/in/samiullahmemon-956393209",
      x: "https://x.com/MemonSamiullah4",
    },
  },
  {
    key: "fiverr",
    value: {
      profile_url: "https://www.fiverr.com/ismailmemon1",
      rating: 4.9,
      reviews: 61,
      level: "Level 2",
    },
  },
];
